name: Update Latest Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once every day at midnight UTC
  workflow_dispatch:       # Allows you to manually trigger the workflow

jobs:
  update-readme:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@winniegich"
